language: python
python: 2.7
install: pip install Lektor

script:
  - echo "deploying ..."
  - echo "" >> $STATUSFILE
  - echo "<!--" >> $STATUSFILE
  - echo "last deployed at" >> $STATUSFILE
  - date >> $STATUSFILE
  - echo "from commit $TRAVIS_COMMIT" >> $STATUSFILE
  - echo "by $USER" >> $STATUSFILE
  - echo "-->" >> $STATUSFILE
  - lektor build

deploy:
  provider: script
  script: lektor deploy trustmoresystems
  on:
    branch: master

env:
  global:
  - STATUSFILE=templates/layout.html
  - secure: Tq5y8M+ecJYSf7mpo6S9ZGAqnmlyXmZtBdTrpwTVrTrd2L0qa3kZT/6692PbD8mFBzWgQrijoddtLlQEwXkrFeCBU+rV2Wz95THNL1Gme/meh0uNpHcc3fWOG3sU/4AejLUGpHcYG9and8RSiJvm7SSONwznp9sVa63/p86rb9iID1p9rLcB1Kv57w+ZzyTzJj9hB3IcfGA0kk6M8LIOI8KI7+7pKeuIKghqSwvaU+U61aASYl1XfouOgBsKQRj76LJREDKdbCtu8YWs9U/i77LEZoSdMJcvazPQwdvpvFRcPxo3WeXBjB+3xhg1VKgXPznufuheHL0qgiK0erKUmT0v+esRLwXTVoicaB0vd7YUVb278vMFssNt88Uad+31WcCE/Ms69iTrtqRS7Rr1/ZFTU4LW7hPT4eJdb6SCDQla0qcCDTyqgx4XxZ+ruQOvhuFtJ8+iOXe3vqeuadULVa82zhG+XLTP9mJzXHkJGUYoTSmY1wBhgGafUx/5yh3G+SsCJE+1ocH2RmFs0D54iN6TV7M5Sa+tVQ9zBHG5pkrMXryXabfRu6IyYq3zZH24q1bxJyPCD4aSCCZAZgqBdk21F0SltL/bEEtCJsyMxiNpJPRQRHjVwGiJECsyGvvERgvdCXx3ivoJJXpsjFuEgxbU0nI8VTYJb/7p4x0dwEU=
  - secure: CX9m+gtpvvHoPmSr26Itg/E3vcyiHdmV4bgOqZ12DH3Ecw9KdSpUYTSc0nL6oZdVMqxH50kRwi5bdE9rw2sLsnylUk2m2CZSAtwtDoqu9Rf4urNrW67gZDEfzmw/yP+DBmcWm7O+keaDqxXXk6g/gsiYtVNTSOCry6RnbMpcU5xWaUt0DmS8FgE8OZ1h7G7vdLOOu6zpxmYTP11cnL+zrNLmygsduKEFaN/O1MKHMgFiY9DfqUbEIUmSabb27leq8jQs/5WKs+UFKm3ccelmnO1qINHzdAwuoFwQTcpPSS3LYzk/7mZsGDvt32qpDH+OtYFnS+tpDVgj5qj1ZPYz/zmB+M2N+Hzu35A6/z0vlrN1GPVNyA3yZ/2XgIt7MtYAhtbWe7zGJvUFVI/01UriUewbVjR4vPsj53p5zJ9b8H1i5adhcC+N858RX2Tcj02CLiF79EspusuezsQ+xoF9MmqoFk7CotWBqI+483KYYePZYw0Z+hEzkS05DvS6zDKtEDvbZWrNxXxj4NX+Kj46KWifyzfEfHn9TTAg/4Mli0+aeBO1PzSTRJrYAQ8IFaX0hzC97b1dK8fmNJybdfaQOUh13VjPjtdTn3jM15pYxzC2FK7Tw6JM/UiA2zSID3VxkO+JQQ0llsFhPmlO3yxBOTcUNsVcad3yaOTPiitkSu4=
